### ISSUE TITLE
Why does Alter Mind Blade have this script?

### ISSUE THREAD

**Issue by IronGolem** [shadowchemosh/HL-Pack-3PP#25]
In working on the Soulbolt archetype, I copied the Alter Mind Blade bladeskill to create its Mind Bolt-oriented counterpart.  I noticed that there's an eval script on the skill that, as far as I can tell, basically says "Whichever blade type we've chosen, give the hero the tags from the OTHER blade types".  Before I make it do the same thing for Mind Bolts, I want to understand why this is done, but I have not been able to figure out so far.

In fact, reading the description of what these bladeskills do, I'm not even sure why there's any need for any logic at all.  Isn't it just letting the character change their weapon type on the fly instead of requiring a full-round action?

**Comment by shadowchemosh** [comment]
If it did anything at one point it does nothing now.  The "thingid.?" it is looking for are not valid.  So this blade skill does need to be fixed though.  It should allow a "fourth" option of forming a 1H and Light mind blade set.  So that part needs to be fixed.  But the current script can be totally deleted.

**Comment by shadowchemosh** [comment]
Fixed in commit eb4bb7b1bcb0d8bc3a686357e7f2fd6f2e3051c2.
