### ISSUE TITLE
Ultimate Psionics - Soul Blade Archetype - Gifted Blade

### ISSUE THREAD

**Issue by nullPointerMV** [shadowchemosh/HL-Pack-3PP#33]
Hi, I saw some others in the community had asked for fast-forwards on specific archetypes, could the Gifted Blade archetype be added to the list?

**Comment by shadowchemosh** [comment]
You can always ask! Just not any guarantee of course that it makes it faster.  Lots of little UP stuff left to do.

**Comment by psych777** [comment]
thought i would give a shot at this. i started it but have run into a problem. starting at 3rd level the gifted blade 'knows' a power. so when you add the 3rd level of soulknife the soulknife tab changes...the full list of things (like selecting which version of mindblade and the ability to change it) disappears and is replaced by the ability to choose a power. how do i get the powers to show up as a 4th ability and not replace the other list of items....
2nd lvl soulknife:
![image](https://cloud.githubusercontent.com/assets/10572815/6535001/83dbf12a-c439-11e4-892d-38349e9dfba8.png)

3rd lvl soulknife:
![image](https://cloud.githubusercontent.com/assets/10572815/6535017/a3757d4e-c439-11e4-834c-07d89c5cf992.png)

**Comment by IronGolem** [comment]
The class specials haven't gone anywhere, they're just not being shown by default.  When Hero Lab shows a class spells (or some equivalent like psionics), the class specials are hidden away so that you have to use that "Special Abilities" button at the upper left to show them.  The abilities are still there, of course, just not shown by default.

To my knowledge, there is no way to change this behavior.

**Comment by psych777** [comment]
ahhh...nice...would never have thought to click that. thanks!

**Comment by psych777** [comment]
pushed the archetype up. its first archetype i've done so hopefully i didn't miss anything...
