### ISSUE TITLE
Ultimate Psionics & Path of War Expanded: Collective Feats

### ISSUE THREAD

**Issue by IronGolem** [shadowchemosh/HL-Pack-3PP#60]
Several feats modify the Collective ability which appears on a few classes (Tactician, Vitalist, Zealot), but their effects are not yet scripted.  As far as I know the feat list is as follows:

Enlarged collective
Expanded Collective
Expansive Collective
Unbreakable Collective

**Comment by IronGolem** [comment]
Currently awaiting some answers from DSP about how multiple instance of Collective work before I do the scripting work for these feats.  I'm hoping that I'll be able to set up Collective as a generic ability that the various class features can bootstrap and modify, and that the feats can further modify.

**Comment by delawless** [comment]
If you are asking about how levels in classes stack, they do.

**Comment by IronGolem** [comment]
That's my main concern, yes.  But there's also a question of ability scores; all three base classes with this ability add a different ability score to the maximum membership of the collective, and I'd like to be sure about whether they stack or overlap in those cases.

You wouldn't happen to have a link verifying the level stacking, would you?

**Comment by delawless** [comment]
I don’t have a link, it was a question that was asked and answered in the older Dreamscarred press forums.

 

Essentially, if you had a collective through vitalist and a collective through tactician (wis and int), the levels for the limit on number of members stacked.  I don’t recall any specific answer based on the count based on ability score.  

 

As far as the count based on ability score, that’s the unanswered question, but in order to make them not more powerful than single classed collective users, I would suggest taking the largest collective member count ability and that is the one used for all collective related effects.  But that isn’t DSP official.

**Comment by delawless** [comment]
Got your answer.  Use the ability score that gives the highest collective
member count:

http://dreamscarred.com/topic/collectives-from-multiple-classes/

**Comment by IronGolem** [comment]
Works for me.  I figured that would probably be the case, but DSP tends to be a little more biased towards PC strength than Paizo so I wasn't sure.  Thanks!
